### ISSUE TITLE
Autoplay issue

### ISSUE THREAD

**Issue by uzman** [AbeWang/TrailerPlayer#2]
Hi,
If the autoplay=false;
activity indicator spins forever. It displays the pause icon. But it must show the play icon and thumbnail image.
It shows the thumbnail at first, but It shows blank screen after it.

```
        let item = TrailerPlayerItem(
            url: URL(string: "https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8"),
            thumbnailUrl: URL(string: "https://upload.cc/i1/2021/10/04/qGNK3M.png"),
            autoPlay: false)

```
You can check it in your example code.

Can you fix please?

**Comment by AbeWang** [comment]
Hi @uzman , this issue has been fixed. (v1.4.8)
You can refer code below or sample code:
```swift
let item = TrailerPlayerItem(
            url: URL(string: "..."),
            thumbnailUrl: URL(string: "..."),
            autoPlay: false)
...
playerView.manualPlayButton = button // your manualPlay button
```
https://user-images.githubusercontent.com/1064039/152757734-ed4a201b-eb7e-43a7-9e36-94307fa01611.mp4
